#!/usr/bin/env bash
set -euo pipefail
SERVICE="${SERVICE:-order-service}"
SCAN_FAIL_SEVERITY="${SCAN_FAIL_SEVERITY:-high}"
COSIGN_VERIFY="${COSIGN_VERIFY:-0}"
make pipeline SERVICE="$SERVICE" SCAN_FAIL_SEVERITY="$SCAN_FAIL_SEVERITY" COSIGN_VERIFY="$COSIGN_VERIFY"
